require("nvim-treesitter.configs").setup({
    highlight = { enable = true },
	indent = { enable = true },
	context_commentstring = { enable = true, enable_autocmd = false },
	ensure_installed = {
		"bash",
		"go",
		"vimdoc",
		"html",
		"java",
		"javascript",
		"json",
		"lua",
		"markdown",
		"markdown_inline",
		"python",
		"query",
		"regex",
		"rust",
		"svelte",
		--"tsx",
		"typescript",
		"vim",
		"yaml",
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<C-space>",
			node_incremental = "<C-space>",
			scope_incremental = "<nop>",
			node_decremental = "<bs>",
		},
	}
})
